services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KRG\Bundle\MessengerBundle\Registry\RepositoryRegistry: ~
  KRG\Bundle\MessengerBundle\Message\MessageBus\QueryBus: ~

  KRG\Bundle\MessengerBundle\ParamConverter\:
    resource: '../../ParamConverter/*'
    tags:
      - { name: request.param_converter, priority: -2 }

  KRG\Bundle\MessengerBundle\Message\QueryHandler\:
    resource: '../../Message/QueryHandler/*QueryHandler.php'
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: query.bus }

  KRG\Bundle\MessengerBundle\Message\CommandHandler\:
    resource: '../../Message/CommandHandler/*CommandHandler.php'
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  KRG\Bundle\MessengerBundle\Action\:
    resource: '../../Action'
    tags: ['controller.service_arguments']

  KRG\Bundle\MessengerBundle\Service\:
    resource: '../../Service'
